<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_697e0e6630e10',
	'title' => 'post',
	'fields' => array(
		array(
			'key' => 'field_697e0e66a6994',
			'label' => 'Obras',
			'name' => 'related_projects',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Seleccioná uno o más proyectos de obra vinculados a esta nota.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'project',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_697e05025e85d',
	'title' => 'project',
	'fields' => array(
		array(
			'key' => 'field_697e0502309ee',
			'label' => 'ID',
			'name' => 'code',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'menu_order' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_697e0733309f0',
			'label' => 'Resumen',
			'name' => 'short_description',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'menu_order' => 2,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_697e075f309f2',
			'label' => 'Tipo',
			'name' => 'type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 3,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Pavimentación' => 'Pavimentación',
				'Apertura' => 'Apertura',
				'Duplicación' => 'Duplicación',
				'Colectoras' => 'Colectoras',
				'Ampliación carriles' => 'Ampliación carriles',
				'Puente' => 'Puente',
				'Rotonda' => 'Rotonda',
				'Túnel' => 'Túnel',
			),
			'default_value' => 'Pavimentación',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_697e07b8309f3',
			'label' => 'Tipo de duplicación',
			'name' => 'duplication_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 4,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_697e075f309f2',
						'operator' => '==',
						'value' => 'Duplicación',
					),
				),
			),
						'key' => 'field_697e08d0309f8',
						'label' => 'Longitud',
						'name' => 'length',
				'id' => '',
						'type' => 'number',
			'choices' => array(
				'Autopista' => 'Autopista',
						'menu_order' => 5,
				'Travesía urbana' => 'Travesía urbana',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'allow_in_bindings' => 0,
						'min' => '',
						'max' => '',
			'ui' => 0,
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '',
		),
		array(
						'key' => 'field_697e08e1309f9',
						'label' => 'Tramos',
						'name' => 'sections',
			'aria-label' => '',
						'type' => 'text',
			'instructions' => '',
						'required' => 0,
						'menu_order' => 6,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
						'default_value' => '',
						'maxlength' => '',
			'type' => 'select',
			'menu_order' => 7,
						'prepend' => '',
						'append' => '',
				'width' => '',
				'class' => '',
						'key' => 'field_697e0812309f5',
						'label' => 'Estado',
						'name' => 'state',
				'Proyecto' => 'Proyecto',
						'type' => 'select',
				'Adjudicado' => 'Adjudicado',
						'required' => 1,
						'menu_order' => 7,
				'Finalizado' => 'Finalizado',
			),
			'default_value' => 'Proyecto',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
						'choices' => array(
							'Proyecto' => 'Proyecto',
							'En licitación' => 'En licitación',
							'Adjudicado' => 'Adjudicado',
							'En obras' => 'En obras',
							'Paralizado' => 'Paralizado',
							'Finalizado' => 'Finalizado',
						),
						'default_value' => 'Proyecto',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
			'placeholder' => '',
						'ui' => 0,
						'ajax' => 0,
			'create_options' => 0,
						'create_options' => 0,
						'save_options' => 0,
			'key' => 'field_697e086f309f6',
			'label' => 'Avance',
						'key' => 'field_697e086f309f6',
						'label' => 'Avance',
						'name' => 'progress',
			'instructions' => '',
						'type' => 'number',
			'menu_order' => 8,
			'conditional_logic' => 0,
						'menu_order' => 8,
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'min' => '',
						'default_value' => 0,
						'min' => '',
						'max' => '',
			'prepend' => '',
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '',
			'append' => '',
		),
						'key' => 'field_697e69f135800',
						'label' => 'Última actualización avance',
						'name' => 'progress_updated_on',
			'name' => 'end_date',
						'type' => 'date_picker',
			'type' => 'date_picker',
			'instructions' => '',
						'menu_order' => 9,
			'menu_order' => 15,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
						'display_format' => 'd/m/Y',
						'return_format' => 'd/m/Y',
						'first_day' => 1,
						'default_to_current_date' => 0,
			'first_day' => 1,
			'key' => 'field_697e08d0309f8',
			'label' => 'Longitud',
						'key' => 'field_697e0800309f4',
						'label' => 'Pliego de licitación',
						'name' => 'tender_documents',
			'instructions' => '',
						'type' => 'wysiwyg',
			'menu_order' => 5,
			'conditional_logic' => 0,
						'menu_order' => 10,
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_697e69e0357ff',
						'label' => 'Plazo',
						'name' => 'duration',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'menu_order' => 11,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
		),
		array(
			'key' => 'field_697e08e1309f9',
			'label' => 'Tramos',
			'name' => 'sections',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 6,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_697e08fd309fa',
			'label' => 'Inicio de construcción',
			'name' => 'start_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 14,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_697e0931309fb',
			'label' => 'Fecha de licitación',
			'name' => 'bid_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 12,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_697e0961309fc',
			'label' => 'Fecha de adjudicación',
			'name' => 'award_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 13,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_697e08fd309fa',
			'label' => 'Inicio de construcción',
			'name' => 'start_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 14,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_697e088d309f7',
			'label' => 'Finalización',
			'name' => 'end_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 15,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_697e0b20309fe',
			'label' => 'Regiones',
			'name' => 'regions',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 16,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_697e09da309fd',
			'label' => 'Rutas',
			'name' => 'roads',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 1,
			'menu_order' => 17,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'post_tag',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_697e0b52309ff',
			'label' => 'Imagen',
			'name' => 'image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 18,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_697e0b821550c',
			'label' => 'Mapa',
			'name' => 'map',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'menu_order' => 19,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'project',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );
} );


?>